{% set name = "qds-sdk" %}
{% set snakename = "qds_sdk" %}
{% set version = "1.16.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ snakename }}-{{ version }}.tar.gz
  sha256: 28850682afcf3ab0f2a74a9fd442715519db3ee2ba91c7ecb0b1a56773748ffd

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - requests >=1.0.3
    - boto >=2.1.1
    - six >=1.2.0
    - urllib3 >=1.0.2
    - inflection >=0.3.1

test:
  imports:
    - qds_sdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/qubole/qds-sdk-py
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Python SDK for coding to the Qubole Data Service API

extra:
  recipe-maintainers:
    - jan-janssen
