{% set name = "qds-sdk" %}
{% set snakename = "qds_sdk" %}
{% set version = "1.13.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2a59836b4419094096cd46dc307c8554147eeaa837a59766ca9777b5a2adde29" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ snakename }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - requests >=1.0.3
    - boto >=2.1.1
    - six >=1.2.0
    - urllib3 >=1.0.2
    - inflection >=0.3.1

test:
  imports:
    - qds_sdk

about:
  home: https://github.com/qubole/qds-sdk-py
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Python SDK for coding to the Qubole Data Service API'

extra:
  recipe-maintainers:
    - pmlandwehr
